server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: STUDENT-SERVICE
              uri: lb://STUDENT-SERVICE
              predicates:
                - Path=/api/student/**
            - id: SCHOOL-SERVICE
              uri: lb://SCHOOL-SERVICE
              predicates:
                - Path=/api/school/**
  datasource:
    url: ${SCHOOL_DATASOURCE_URL}
    username: ${SCHOOL_DATASOURCE_USERNAME}
    password: ${SCHOOL_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

jwt:
  secret: ${JWT_SECRET}
