server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: STUDENT-SERVICE
              uri: lb://STUDENT-SERVICE
              predicates:
                - Path=/api/student/**
            - id: SCHOOL-SERVICE
              uri: lb://SCHOOL-SERVICE
              predicates:
                - Path=/api/school/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
